name       : libkscreen
version    : 5.11.4
release    : 8
source     :
    - https://cdn.download.kde.org/stable/plasma/5.11.4/libkscreen-5.11.4.tar.xz : ede7b9baa5c236f1637d0236d7c2dc3f9cf3ea30e7a0aecc8fa0d25bbfc1636b
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
optimize   : lto
summary    : KDE's screen management software
description: |
    KDE's screen management software.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xrandr)
    - extra-cmake-modules
    - kwayland-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
