name       : libkscreen
version    : 5.17.4
release    : 42
source     :
    - https://cdn.download.kde.org/stable/plasma/5.17.4/libkscreen-5.17.4.tar.xz : 9d9e1871959948b1d4eea67c070c2123e0c9565ab011e43f3489e7a0f4c4ab29
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
optimize   : lto
summary    : KDE's screen management software
description: |
    KDE's screen management software.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xrandr)
    - extra-cmake-modules
    - kwayland-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
