name       : libkscreen
version    : 5.22.4
release    : 66
source     :
    - https://cdn.download.kde.org/stable/plasma/5.22.4/libkscreen-5.22.4.tar.xz : a211b9b900ced93f506936bfb1e28ec19aa52ebec4cb08e8a15e382114fc557c
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-only
component  : desktop.kde.core
summary    : KDE's screen management software
description: |
    KDE's screen management software.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xrandr)
    - kwayland-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
