name       : libkscreen
version    : 5.27.5
release    : 84
source     :
    - https://cdn.download.kde.org/stable/plasma/5.27.5/libkscreen-5.27.5.tar.xz : 29aff3f28d8706e864b914dea4ab59e5518ed0381bb1c6625f454f08196deb65
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-only
component  : desktop.kde.core
summary    : KDE's screen management software
description: |
    KDE's screen management software.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(Qt5WaylandClient)
    - pkgconfig(xrandr)
    - plasma-wayland-protocols-devel
    - kconfig-devel
    - kwayland-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
