name       : libkscreen
version    : 5.19.4
release    : 51
source     :
    - https://cdn.download.kde.org/stable/plasma/5.19.4/libkscreen-5.19.4.tar.xz : 7140ff923c42cfcffbe4b1b2b15df20736342889c7f29b1d847db353e46c8281
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
optimize   : lto
summary    : KDE's screen management software
description: |
    KDE's screen management software.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xrandr)
    - extra-cmake-modules
    - kwayland-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
