name       : libkscreen
version    : 5.18.4.1
release    : 47
source     :
    - https://cdn.download.kde.org/stable/plasma/5.18.4/libkscreen-5.18.4.1.tar.xz : c42077f927a087744a4619384f2784d117c4d8329e0335d718bb2afa3af68436
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
optimize   : lto
summary    : KDE's screen management software
description: |
    KDE's screen management software.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xrandr)
    - extra-cmake-modules
    - kwayland-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
