name       : libkscreen
version    : 5.23.1
release    : 69
source     :
    - https://cdn.download.kde.org/stable/plasma/5.23.1/libkscreen-5.23.1.tar.xz : 3930d578f55e5d5be95da1f3fe298b15623afcea0a9c73005cb983589204d043
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-only
component  : desktop.kde.core
summary    : KDE's screen management software
description: |
    KDE's screen management software.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(Qt5WaylandClient)
    - pkgconfig(xrandr)
    - plasma-wayland-protocols-devel
    - kwayland-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
