name       : libkscreen
version    : 5.13.2
release    : 18
source     :
    - https://cdn.download.kde.org/stable/plasma/5.13.2/libkscreen-5.13.2.tar.xz : a5629c371a79b7872f72cc212e42d408823fba0f1eb2bd46fb036f657d372517
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
optimize   : lto
summary    : KDE's screen management software
description: |
    KDE's screen management software.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xrandr)
    - extra-cmake-modules
    - kwayland-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
