name       : libkscreen
version    : 5.13.5
release    : 21
source     :
    - https://cdn.download.kde.org/stable/plasma/5.13.5/libkscreen-5.13.5.tar.xz : 9330c34ac709968a6b821d5ae616bab0eb98cd466174dc83c5c6c412d44ee110
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
optimize   : lto
summary    : KDE's screen management software
description: |
    KDE's screen management software.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xrandr)
    - extra-cmake-modules
    - kwayland-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
